configs:
  netdata_client_stream:
    file: ./netdata_client_stream.conf
  netdata_central_config:
    file: ./netdata_central.conf
  netdata_central_stream:
    file: ./netdata_central_stream.conf

services:
  netdata-client:
    image: netdata/netdata
    hostname: "{{.Node.Hostname}}"
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - netdata
    configs:
      - source: netdata_client_stream
        target: /etc/netdata/stream.conf  
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

  netdata_central:
    image: netdata/netdata
    hostname: netdata_central 
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    ports:
      - target: 19999
        published: 19999
        mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - netdata-lib:/var/lib/netdata
    networks:
      - netdata
    configs:
      - source: netdata_central_config
        target: /etc/netdata/netdata.conf  
      - source: netdata_central_stream
        target: /etc/netdata/stream.conf
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.id == tmt6v8upd2s4vbc1umbe2cw43]

networks:
  netdata:
    driver: overlay
    attachable: true

volumes:
  netdata-lib:
