configs:
  netdata_client_config:
    file: ./netdata/netdata_client.yml
  netdata_central_config:
    file: ./netdata/netdata_central.yml
  netdata_central_stream:
    file: ./netdata/netdata_central_stream.yml

services:
  netdata-client:
    image: netdata/netdata
    hostname: "{{.Node.Hostname}}-{{.Node.ID}}"
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - netdata
    configs:
      - source: netdata_client_config
        target: /etc/netdata/stream.conf
    deploy:
      mode: global
      placement:
        constraints: [node.id != i6s98au3wvj5wx7j4lo041ndj]

  netdata_central:
    image: netdata/netdata
    hostname: "netdata_central-{{.Node.ID}}"
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    ports:
      - target: 19999
        published: 19999
        mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - netdata-lib:/var/lib/netdata
    networks:
      netdata:
        aliases:
          - netdata_central
    configs:
      - source: netdata_central_config
        target: /etc/netdata/netdata.conf
      - source: netdata_central_stream
        target: /etc/netdata/stream.conf
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.id == i6s98au3wvj5wx7j4lo041ndj]

networks:
  netdata:
    driver: overlay
    attachable: true

volumes:
  netdata-lib:
