scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "dockerswarm"
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      # Only keep containers that should be running.
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
        regex: .+
        action: keep
      # Use the prometheus-job Swarm label as Prometheus job label.
      - source_labels: [__meta_dockerswarm_container_label_prometheus_job]
        target_label: job
      # Only scrape if within the `hostforge-internal` network.
      - source_labels: [__meta_dockerswarm_network_name]
        regex: hostforge-internal
        action: keep
      # Add docker node label to targets
      - source_labels: [__meta_dockerswarm_node_id]
        target_label: docker_node_id
